image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start
    command: npm install
    command: npx hardhat compile

ports:
  - port: 3000
    onOpen: open-browser
  - port: 8545
    onOpen: ignore

vscode:
  extensions:
    - NomicFoundation.hardhat-solidity
